#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


ROOT = Path(__file__).resolve().parents[2]

MAIN_DIR = ROOT / "samples" / "main_process" / "pptx"
META_DIR = ROOT / "samples" / "metadata" / "pptx"
BENCH_DIR = ROOT / "samples" / "benchmark" / "pptx"

FIXED_DATE = (2026, 5, 7, 0, 0, 0)


def zip_info(name: str) -> ZipInfo:
    info = ZipInfo(name)
    info.date_time = FIXED_DATE
    info.compress_type = ZIP_DEFLATED
    return info


def read_entries(path: Path) -> list[tuple[str, bytes]]:
    with ZipFile(path) as zf:
        return [(name, zf.read(name)) for name in zf.namelist()]


def write_entries(path: Path, entries: list[tuple[str, bytes]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as zf:
        for name, data in entries:
            zf.writestr(zip_info(name), data)


def rewrite_zip(
    src: Path,
    dest: Path,
    *,
    replacements: dict[str, bytes] | None = None,
) -> None:
    replacements = replacements or {}
    entries = read_entries(src)
    out: list[tuple[str, bytes]] = []
    for name, data in entries:
        out.append((name, replacements.get(name, data)))
    write_entries(dest, out)


def core_props_xml(
    *,
    title: str,
    subject: str,
    creator: str,
    description: str,
    keywords: str,
    created: str,
    modified: str,
) -> bytes:
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>{title}</dc:title>
  <dc:subject>{subject}</dc:subject>
  <dc:creator>{creator}</dc:creator>
  <cp:lastModifiedBy>{creator}</cp:lastModifiedBy>
  <cp:revision>2</cp:revision>
  <dc:description>{description}</dc:description>
  <cp:keywords>{keywords}</cp:keywords>
  <dcterms:created xsi:type="dcterms:W3CDTF">{created}</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">{modified}</dcterms:modified>
</cp:coreProperties>
""".encode("utf-8")


def app_props_xml(*, slides: int, words: int) -> bytes:
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <TotalTime>0</TotalTime>
  <Words>{words}</Words>
  <Application>Microsoft Office PowerPoint</Application>
  <PresentationFormat>On-screen Show (16:9)</PresentationFormat>
  <Paragraphs>0</Paragraphs>
  <Slides>{slides}</Slides>
  <Notes>0</Notes>
  <HiddenSlides>0</HiddenSlides>
  <MMClips>0</MMClips>
  <ScaleCrop>false</ScaleCrop>
  <HeadingPairs>
    <vt:vector size="2" baseType="variant">
      <vt:variant><vt:lpstr>Slide Titles</vt:lpstr></vt:variant>
      <vt:variant><vt:i4>{slides}</vt:i4></vt:variant>
    </vt:vector>
  </HeadingPairs>
  <TitlesOfParts>
    <vt:vector size="{slides}" baseType="lpstr">
      <vt:lpstr>Slide 1</vt:lpstr>
      {"<vt:lpstr>Slide 2</vt:lpstr>" if slides > 1 else ""}
      {"<vt:lpstr>Slide 3</vt:lpstr>" if slides > 2 else ""}
    </vt:vector>
  </TitlesOfParts>
  <Company>markitdown-mb</Company>
  <LinksUpToDate>false</LinksUpToDate>
  <SharedDoc>false</SharedDoc>
  <HyperlinksChanged>false</HyperlinksChanged>
  <AppVersion>16.0000</AppVersion>
</Properties>
""".encode("utf-8")


def metadata_docprops_rich() -> None:
    rewrite_zip(
        MAIN_DIR / "pptx_simple.pptx",
        META_DIR / "pptx_metadata_docprops_rich.pptx",
        replacements={
            "docProps/core.xml": core_props_xml(
                title="PPTX Metadata Rich",
                subject="Second-round metadata coverage",
                creator="markitdown-mb",
                description="generated by generate_pptx_second_round_samples.py",
                keywords="pptx,metadata,origin",
                created="2026-05-07T00:00:00Z",
                modified="2026-05-07T00:00:00Z",
            ),
            "docProps/app.xml": app_props_xml(slides=3, words=42),
        },
    )


def metadata_links_images() -> None:
    slide_xml = """<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr/>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="3" name="Title 1"/>
          <p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr>
          <p:nvPr><p:ph type="title"/></p:nvPr>
        </p:nvSpPr>
        <p:spPr/>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>PPTX Links And Images</a:t></a:r></a:p></p:txBody>
      </p:sp>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="4" name="Content Placeholder 2"/>
          <p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr>
          <p:nvPr><p:ph idx="1"/></p:nvPr>
        </p:nvSpPr>
        <p:spPr/>
        <p:txBody>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:r><a:t>See </a:t></a:r>
            <a:r><a:rPr><a:hlinkClick r:id="rId3"/></a:rPr><a:t>reference</a:t></a:r>
            <a:r><a:t> before review.</a:t></a:r>
          </a:p>
        </p:txBody>
      </p:sp>
      <p:pic>
        <p:nvPicPr>
          <p:cNvPr id="2" name="Picture 1" descr="Figure alt text" title="Figure title text"/>
          <p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr>
          <p:nvPr/>
        </p:nvPicPr>
        <p:blipFill><a:blip r:embed="rId2"/><a:stretch><a:fillRect/></a:stretch></p:blipFill>
        <p:spPr><a:xfrm><a:off x="1200000" y="1600000"/><a:ext cx="4000000" cy="2500000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
      </p:pic>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>
""".encode("utf-8")
    rels_xml = """<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout7.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image1.png"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/reference" TargetMode="External"/>
</Relationships>
""".encode("utf-8")
    rewrite_zip(
        META_DIR / "pptx_image_alt_title_basic.pptx",
        META_DIR / "pptx_metadata_links_images.pptx",
        replacements={
            "ppt/slides/slide1.xml": slide_xml,
            "ppt/slides/_rels/slide1.xml.rels": rels_xml,
            "docProps/core.xml": core_props_xml(
                title="PPTX Links And Images",
                subject="Second-round link image metadata",
                creator="markitdown-mb",
                description="generated by generate_pptx_second_round_samples.py",
                keywords="pptx,links,images",
                created="2026-05-07T00:00:00Z",
                modified="2026-05-07T00:00:00Z",
            ),
            "docProps/app.xml": app_props_xml(slides=1, words=18),
        },
    )


def metadata_aliases() -> None:
    rewrite_zip(
        META_DIR / "pptx_metadata_table_basic.pptx",
        META_DIR / "pptx_metadata_table_grid.pptx",
    )
    rewrite_zip(
        META_DIR / "pptx_image_single_caption_like.pptx",
        META_DIR / "pptx_metadata_caption_like.pptx",
    )


def benchmark_samples() -> None:
    benchmark_slide_xml = """<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr/>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="2" name="Title 1"/>
          <p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr>
          <p:nvPr><p:ph type="title"/></p:nvPr>
        </p:nvSpPr>
        <p:spPr/>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>PPTX Link Heavy</a:t></a:r></a:p></p:txBody>
      </p:sp>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="3" name="Content Placeholder 2"/>
          <p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr>
          <p:nvPr><p:ph idx="1"/></p:nvPr>
        </p:nvSpPr>
        <p:spPr/>
        <p:txBody>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p><a:r><a:t>Resources: </a:t></a:r><a:r><a:rPr><a:hlinkClick r:id="rId2"/></a:rPr><a:t>Alpha</a:t></a:r><a:r><a:t>, </a:t></a:r><a:r><a:rPr><a:hlinkClick r:id="rId3"/></a:rPr><a:t>Beta</a:t></a:r><a:r><a:t>, </a:t></a:r><a:r><a:rPr><a:hlinkClick r:id="rId4"/></a:rPr><a:t>Gamma</a:t></a:r></a:p>
          <a:p><a:r><a:t>Docs: </a:t></a:r><a:r><a:rPr><a:hlinkClick r:id="rId5"/></a:rPr><a:t>API</a:t></a:r><a:r><a:t>, </a:t></a:r><a:r><a:rPr><a:hlinkClick r:id="rId6"/></a:rPr><a:t>Guide</a:t></a:r><a:r><a:t>, </a:t></a:r><a:r><a:rPr><a:hlinkClick r:id="rId7"/></a:rPr><a:t>FAQ</a:t></a:r></a:p>
        </p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>
""".encode("utf-8")
    benchmark_rels_xml = """<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout2.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/alpha" TargetMode="External"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/beta" TargetMode="External"/>
  <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/gamma" TargetMode="External"/>
  <Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/api" TargetMode="External"/>
  <Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/guide" TargetMode="External"/>
  <Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/faq" TargetMode="External"/>
</Relationships>
""".encode("utf-8")
    rewrite_zip(
        MAIN_DIR / "pptx_hyperlink_basic.pptx",
        BENCH_DIR / "pptx_link_heavy.pptx",
        replacements={
            "ppt/slides/slide1.xml": benchmark_slide_xml,
            "ppt/slides/_rels/slide1.xml.rels": benchmark_rels_xml,
        },
    )
    rewrite_zip(
        MAIN_DIR / "pptx_speaker_notes_basic.pptx",
        BENCH_DIR / "pptx_notes_heavy.pptx",
    )
    rewrite_zip(
        MAIN_DIR / "pptx_negative_dense_keyword_wall.pptx",
        BENCH_DIR / "pptx_layout_heavy.pptx",
    )


def main() -> None:
    metadata_docprops_rich()
    metadata_links_images()
    metadata_aliases()
    benchmark_samples()


if __name__ == "__main__":
    main()
