from __future__ import annotations

import shlex
from pathlib import Path

from .config import ConfigBundle, PlatformInfo
from .package_manager import ToolState
from .utils import stable_json_dumps, write_text_if_changed
from .venv_sync import VenvState


def runtime_args_snapshot(bundle: ConfigBundle, profile_name: str) -> dict:
    stable_env = dict(bundle.runtime_args["stable_env"])
    commands = dict(bundle.runtime_args["commands"])
    paddle = dict(bundle.runtime_args["paddle"])
    if profile_name == "balance":
        return {
            "stable_env": stable_env,
            "commands": {
                "pdftoppm": commands["pdftoppm"],
                "tesseract": commands["tesseract"],
            },
        }
    if profile_name == "audio":
        return {
            "stable_env": stable_env,
            "commands": {"ffmpeg": commands["ffmpeg"]},
        }
    if profile_name == "accurate":
        return {
            "stable_env": stable_env,
            "commands": {
                "pdftoppm": commands["pdftoppm"],
                "tesseract": commands["tesseract"],
            },
            "paddle": paddle,
        }
    return {"stable_env": stable_env}


def profile_fingerprint(
    *,
    bundle: ConfigBundle,
    profile_name: str,
    platform: PlatformInfo,
    tools: dict[str, ToolState],
    venv: VenvState | None,
    models: dict[str, dict],
) -> dict:
    payload: dict[str, object] = {
        "profile": profile_name,
        "platform": {
            "arch": platform.arch,
            "manager": platform.manager,
            "os": platform.os_name,
            "key": platform.key,
        },
        "runtime_args": runtime_args_snapshot(bundle, profile_name),
        "system_tools": {
            tool_name: {
                "binary_sha256": tool.binary_sha256,
                "command_path": tool.command_path,
                "managed_record": tool.record_path,
                "managed_symlink": tool.symlink_path,
                "packages": tool.packages,
                "version": tool.version,
                "version_args": tool.version_args,
                "version_fragment": tool.version_fragment,
                "version_line": tool.version_line,
            }
            for tool_name, tool in sorted(tools.items())
        },
    }
    if venv is not None:
        payload["python"] = {
            "lock_path": venv.lock_path,
            "lock_sha256": venv.lock_sha256,
            "packages": venv.packages,
            "python_path": venv.python_path,
            "python_version": venv.python_version,
            "venv_path": venv.venv_path,
        }
    if models:
        payload["models"] = {key: value for key, value in sorted(models.items())}
    return payload


def render_env_file(exports: dict[str, str], stable_env: dict[str, str]) -> str:
    lines = [
        "# Generated by tools/env/lib/manage.py",
        "# shellcheck shell=bash",
    ]
    for key, value in stable_env.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    for key, value in exports.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    return "\n".join(lines) + "\n"


def write_env_file(path: Path, exports: dict[str, str], stable_env: dict[str, str]) -> None:
    write_text_if_changed(path, render_env_file(exports, stable_env))


def render_fingerprint(payload: dict) -> str:
    return stable_json_dumps(payload)


def write_fingerprint(path: Path, payload: dict) -> None:
    write_text_if_changed(path, render_fingerprint(payload))
