from __future__ import annotations

import shlex
from pathlib import Path

from .config import ConfigBundle, PlatformInfo
from .package_manager import ToolState
from .utils import stable_json_dumps, write_text_if_changed
from .venv_sync import VenvState


BENCH_ENV = {
    "TZ": "UTC",
    "LANG": "en_US.UTF-8",
    "LC_ALL": "en_US.UTF-8",
    "PYTHONHASHSEED": "0",
    "OMP_NUM_THREADS": "1",
    "MKL_NUM_THREADS": "1",
    "OPENBLAS_NUM_THREADS": "1",
    "VECLIB_MAXIMUM_THREADS": "1",
    "NUMEXPR_NUM_THREADS": "1",
}


def profile_fingerprint(
    *,
    bundle: ConfigBundle,
    profile_name: str,
    platform: PlatformInfo,
    tools: dict[str, ToolState],
    venv: VenvState | None,
) -> dict:
    payload: dict[str, object] = {
        "profile": profile_name,
        "platform": {
            "arch": platform.arch,
            "manager": platform.manager,
            "os": platform.os_name,
            "key": platform.key,
        },
        "stable_env": BENCH_ENV,
        "system_tools": {
            tool_name: {
                "binary_sha256": tool.binary_sha256,
                "command_path": tool.command_path,
                "managed_record": tool.record_path,
                "managed_symlink": tool.symlink_path,
                "packages": tool.packages,
                "version": tool.version,
                "version_args": tool.version_args,
                "version_fragment": tool.version_fragment,
                "version_line": tool.version_line,
            }
            for tool_name, tool in sorted(tools.items())
        },
    }
    if venv is not None:
        payload["python"] = {
            "lock_path": venv.lock_path,
            "lock_sha256": venv.lock_sha256,
            "packages": venv.packages,
            "python_path": venv.python_path,
            "python_version": venv.python_version,
            "venv_path": venv.venv_path,
        }
    return payload


def render_env_file(exports: dict[str, str], stable_env: dict[str, str]) -> str:
    lines = [
        "# Generated by tools/env/lib/manage.py",
        "# shellcheck shell=bash",
    ]
    for key, value in stable_env.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    for key, value in exports.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    return "\n".join(lines) + "\n"


def write_env_file(path: Path, exports: dict[str, str], stable_env: dict[str, str]) -> None:
    write_text_if_changed(path, render_env_file(exports, stable_env))


def render_fingerprint(payload: dict) -> str:
    return stable_json_dumps(payload)


def write_fingerprint(path: Path, payload: dict) -> None:
    write_text_if_changed(path, render_fingerprint(payload))
